/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#ea2804",
        "primary-deep": "#c01f00",
        "on-primary": "#ffffff",
        ink: "#202020",
        body: "#3a3a3a",
        charcoal: "#575757",
        mute: "#646464",
        ash: "#8d8d8d",
        stone: "#bbbbbb",
        "on-dark": "#fcfcfc",
        "on-dark-mute": "rgba(252,252,252,0.72)",
        canvas: "#f9f7f3",
        "surface-bone": "#f3f0e8",
        "surface-card": "#ffffff",
        "surface-dark": "#202020",
        "surface-deep": "#000000",
        hairline: "rgba(32,32,32,0.12)",
        "hairline-strong": "#202020",
        "divider-dark": "rgba(255,255,255,0.2)",
        "hero-warm": "#ea2804",
        "hero-glow": "#ff6a3d",
        "hero-pink": "#f4a8a0",
        "badge-success": "#2b9a66",
        link: "#ea2804",
        "ring-focus": "rgba(59,130,246,0.5)",
        "github-dark": "#24292e",
      },
      fontFamily: {
        display: ["Outfit", "Space Grotesk", "sans-serif"],
        body: ["Space Grotesk", "Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        none: "0px",
        xs: "4px",
        sm: "6px",
        md: "10px",
        lg: "16px",
        full: "9999px",
      },
      spacing: {
        xxs: "2px",
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        xxl: "32px",
        xxxl: "48px",
        section: "96px",
        band: "160px",
      }
    },
  },
  plugins: [],
}
